//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinersClubOnline.Services.Client.SeguridadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.online.diners.pe/", ConfigurationName="SeguridadService.Seguridad")]
    public interface Seguridad {
        
        // CODEGEN: Generating message contract since the operation CambiarClaveDigital is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse1 CambiarClaveDigital(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse1> CambiarClaveDigitalAsync(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest request);
        
        // CODEGEN: Generating message contract since the operation login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DinersClubOnline.Services.Client.SeguridadService.loginResponse1 login(DinersClubOnline.Services.Client.SeguridadService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.loginResponse1> loginAsync(DinersClubOnline.Services.Client.SeguridadService.loginRequest request);
        
        // CODEGEN: Generating message contract since the operation pruebaws is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse1 pruebaws(DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse1> pruebawsAsync(DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest request);
        
        // CODEGEN: Generating message contract since the operation registrarClaveDigital is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse1 registrarClaveDigital(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse1> registrarClaveDigitalAsync(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest request);
        
        // CODEGEN: Generating message contract since the operation validarTarjeta is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse1 validarTarjeta(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse1> validarTarjetaAsync(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest request);
        
        // CODEGEN: Generating message contract since the operation validarTarjetaUsuario is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse1 validarTarjetaUsuario(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse1> validarTarjetaUsuarioAsync(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class CambiarClaveDigital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestCambiarClaveDigital arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestCambiarClaveDigital arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class requestCambiarClaveDigital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveDigitalField;
        
        private string idUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveDigital {
            get {
                return this.claveDigitalField;
            }
            set {
                this.claveDigitalField = value;
                this.RaisePropertyChanged("claveDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class responseValidarTarjetaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveDigitalRegistradaField;
        
        private string codigoMensajeField;
        
        private string idUsuarioField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveDigitalRegistrada {
            get {
                return this.claveDigitalRegistradaField;
            }
            set {
                this.claveDigitalRegistradaField = value;
                this.RaisePropertyChanged("claveDigitalRegistrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class validarTarjetaUsuarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseValidarTarjetaUsuario returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseValidarTarjetaUsuario @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class requestValidarTarjetaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveATMField;
        
        private string numeroTarjetaField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveATM {
            get {
                return this.claveATMField;
            }
            set {
                this.claveATMField = value;
                this.RaisePropertyChanged("claveATM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class validarTarjetaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestValidarTarjetaUsuario arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestValidarTarjetaUsuario arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class responseValidarTarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string contieneClaveDigitalField;
        
        private string idTarjetaField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contieneClaveDigital {
            get {
                return this.contieneClaveDigitalField;
            }
            set {
                this.contieneClaveDigitalField = value;
                this.RaisePropertyChanged("contieneClaveDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idTarjeta {
            get {
                return this.idTarjetaField;
            }
            set {
                this.idTarjetaField = value;
                this.RaisePropertyChanged("idTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class validarTarjetaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseValidarTarjeta returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseValidarTarjeta @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class requestValidarTarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveATMField;
        
        private string numeroTarjetaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveATM {
            get {
                return this.claveATMField;
            }
            set {
                this.claveATMField = value;
                this.RaisePropertyChanged("claveATM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class validarTarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestValidarTarjeta arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestValidarTarjeta arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class responseRegistrarClaveDigital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string idUsuarioField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class registrarClaveDigitalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseRegistrarClaveDigital returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseRegistrarClaveDigital @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class requestRegistrarClaveDigital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveDigitalField;
        
        private string emailField;
        
        private string idFacebookField;
        
        private string idImagenField;
        
        private string idTarjetaField;
        
        private string numeroCelularField;
        
        private string operadorTelefonicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveDigital {
            get {
                return this.claveDigitalField;
            }
            set {
                this.claveDigitalField = value;
                this.RaisePropertyChanged("claveDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idFacebook {
            get {
                return this.idFacebookField;
            }
            set {
                this.idFacebookField = value;
                this.RaisePropertyChanged("idFacebook");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idImagen {
            get {
                return this.idImagenField;
            }
            set {
                this.idImagenField = value;
                this.RaisePropertyChanged("idImagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idTarjeta {
            get {
                return this.idTarjetaField;
            }
            set {
                this.idTarjetaField = value;
                this.RaisePropertyChanged("idTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroCelular {
            get {
                return this.numeroCelularField;
            }
            set {
                this.numeroCelularField = value;
                this.RaisePropertyChanged("numeroCelular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string operadorTelefonico {
            get {
                return this.operadorTelefonicoField;
            }
            set {
                this.operadorTelefonicoField = value;
                this.RaisePropertyChanged("operadorTelefonico");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class registrarClaveDigital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestRegistrarClaveDigital arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestRegistrarClaveDigital arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class pruebaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseParamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string responseParam {
            get {
                return this.responseParamField;
            }
            set {
                this.responseParamField = value;
                this.RaisePropertyChanged("responseParam");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class pruebawsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pruebaResponse prueba_ws_resultsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pruebaResponse prueba_ws_resultset {
            get {
                return this.prueba_ws_resultsetField;
            }
            set {
                this.prueba_ws_resultsetField = value;
                this.RaisePropertyChanged("prueba_ws_resultset");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class pruebaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestParamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string requestParam {
            get {
                return this.requestParamField;
            }
            set {
                this.requestParamField = value;
                this.RaisePropertyChanged("requestParam");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class pruebaws : object, System.ComponentModel.INotifyPropertyChanged {
        
        private pruebaRequest prueba_ws_requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pruebaRequest prueba_ws_request {
            get {
                return this.prueba_ws_requestField;
            }
            set {
                this.prueba_ws_requestField = value;
                this.RaisePropertyChanged("prueba_ws_request");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class responseLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string idUsuarioField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class loginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseLogin returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseLogin @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class requestLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveDigitalField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string claveDigital {
            get {
                return this.claveDigitalField;
            }
            set {
                this.claveDigitalField = value;
                this.RaisePropertyChanged("claveDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class login : object, System.ComponentModel.INotifyPropertyChanged {
        
        private requestLogin arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public requestLogin arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class responseCambiarClaveDigital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.online.diners.pe/")]
    public partial class CambiarClaveDigitalResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseCambiarClaveDigital returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseCambiarClaveDigital @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarClaveDigitalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigital CambiarClaveDigital;
        
        public CambiarClaveDigitalRequest() {
        }
        
        public CambiarClaveDigitalRequest(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigital CambiarClaveDigital) {
            this.CambiarClaveDigital = CambiarClaveDigital;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarClaveDigitalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse CambiarClaveDigitalResponse;
        
        public CambiarClaveDigitalResponse1() {
        }
        
        public CambiarClaveDigitalResponse1(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse CambiarClaveDigitalResponse) {
            this.CambiarClaveDigitalResponse = CambiarClaveDigitalResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.login login;
        
        public loginRequest() {
        }
        
        public loginRequest(DinersClubOnline.Services.Client.SeguridadService.login login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.loginResponse loginResponse;
        
        public loginResponse1() {
        }
        
        public loginResponse1(DinersClubOnline.Services.Client.SeguridadService.loginResponse loginResponse) {
            this.loginResponse = loginResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebawsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.pruebaws pruebaws;
        
        public pruebawsRequest() {
        }
        
        public pruebawsRequest(DinersClubOnline.Services.Client.SeguridadService.pruebaws pruebaws) {
            this.pruebaws = pruebaws;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebawsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse pruebawsResponse;
        
        public pruebawsResponse1() {
        }
        
        public pruebawsResponse1(DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse pruebawsResponse) {
            this.pruebawsResponse = pruebawsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarClaveDigitalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigital registrarClaveDigital;
        
        public registrarClaveDigitalRequest() {
        }
        
        public registrarClaveDigitalRequest(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigital registrarClaveDigital) {
            this.registrarClaveDigital = registrarClaveDigital;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarClaveDigitalResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse registrarClaveDigitalResponse;
        
        public registrarClaveDigitalResponse1() {
        }
        
        public registrarClaveDigitalResponse1(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse registrarClaveDigitalResponse) {
            this.registrarClaveDigitalResponse = registrarClaveDigitalResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.validarTarjeta validarTarjeta;
        
        public validarTarjetaRequest() {
        }
        
        public validarTarjetaRequest(DinersClubOnline.Services.Client.SeguridadService.validarTarjeta validarTarjeta) {
            this.validarTarjeta = validarTarjeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarTarjetaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse validarTarjetaResponse;
        
        public validarTarjetaResponse1() {
        }
        
        public validarTarjetaResponse1(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse validarTarjetaResponse) {
            this.validarTarjetaResponse = validarTarjetaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarTarjetaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuario validarTarjetaUsuario;
        
        public validarTarjetaUsuarioRequest() {
        }
        
        public validarTarjetaUsuarioRequest(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuario validarTarjetaUsuario) {
            this.validarTarjetaUsuario = validarTarjetaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarTarjetaUsuarioResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.diners.pe/", Order=0)]
        public DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse validarTarjetaUsuarioResponse;
        
        public validarTarjetaUsuarioResponse1() {
        }
        
        public validarTarjetaUsuarioResponse1(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse validarTarjetaUsuarioResponse) {
            this.validarTarjetaUsuarioResponse = validarTarjetaUsuarioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SeguridadChannel : DinersClubOnline.Services.Client.SeguridadService.Seguridad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SeguridadClient : System.ServiceModel.ClientBase<DinersClubOnline.Services.Client.SeguridadService.Seguridad>, DinersClubOnline.Services.Client.SeguridadService.Seguridad {
        
        public SeguridadClient() {
        }
        
        public SeguridadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SeguridadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse1 DinersClubOnline.Services.Client.SeguridadService.Seguridad.CambiarClaveDigital(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest request) {
            return base.Channel.CambiarClaveDigital(request);
        }
        
        public DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse CambiarClaveDigital(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigital CambiarClaveDigital1) {
            DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest();
            inValue.CambiarClaveDigital = CambiarClaveDigital1;
            DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse1 retVal = ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).CambiarClaveDigital(inValue);
            return retVal.CambiarClaveDigitalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse1> DinersClubOnline.Services.Client.SeguridadService.Seguridad.CambiarClaveDigitalAsync(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest request) {
            return base.Channel.CambiarClaveDigitalAsync(request);
        }
        
        public System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalResponse1> CambiarClaveDigitalAsync(DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigital CambiarClaveDigital) {
            DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.CambiarClaveDigitalRequest();
            inValue.CambiarClaveDigital = CambiarClaveDigital;
            return ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).CambiarClaveDigitalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinersClubOnline.Services.Client.SeguridadService.loginResponse1 DinersClubOnline.Services.Client.SeguridadService.Seguridad.login(DinersClubOnline.Services.Client.SeguridadService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public DinersClubOnline.Services.Client.SeguridadService.loginResponse login(DinersClubOnline.Services.Client.SeguridadService.login login1) {
            DinersClubOnline.Services.Client.SeguridadService.loginRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.loginRequest();
            inValue.login = login1;
            DinersClubOnline.Services.Client.SeguridadService.loginResponse1 retVal = ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).login(inValue);
            return retVal.loginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.loginResponse1> DinersClubOnline.Services.Client.SeguridadService.Seguridad.loginAsync(DinersClubOnline.Services.Client.SeguridadService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.loginResponse1> loginAsync(DinersClubOnline.Services.Client.SeguridadService.login login) {
            DinersClubOnline.Services.Client.SeguridadService.loginRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.loginRequest();
            inValue.login = login;
            return ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse1 DinersClubOnline.Services.Client.SeguridadService.Seguridad.pruebaws(DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest request) {
            return base.Channel.pruebaws(request);
        }
        
        public DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse pruebaws(DinersClubOnline.Services.Client.SeguridadService.pruebaws pruebaws1) {
            DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest();
            inValue.pruebaws = pruebaws1;
            DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse1 retVal = ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).pruebaws(inValue);
            return retVal.pruebawsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse1> DinersClubOnline.Services.Client.SeguridadService.Seguridad.pruebawsAsync(DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest request) {
            return base.Channel.pruebawsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.pruebawsResponse1> pruebawsAsync(DinersClubOnline.Services.Client.SeguridadService.pruebaws pruebaws) {
            DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.pruebawsRequest();
            inValue.pruebaws = pruebaws;
            return ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).pruebawsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse1 DinersClubOnline.Services.Client.SeguridadService.Seguridad.registrarClaveDigital(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest request) {
            return base.Channel.registrarClaveDigital(request);
        }
        
        public DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse registrarClaveDigital(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigital registrarClaveDigital1) {
            DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest();
            inValue.registrarClaveDigital = registrarClaveDigital1;
            DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse1 retVal = ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).registrarClaveDigital(inValue);
            return retVal.registrarClaveDigitalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse1> DinersClubOnline.Services.Client.SeguridadService.Seguridad.registrarClaveDigitalAsync(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest request) {
            return base.Channel.registrarClaveDigitalAsync(request);
        }
        
        public System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalResponse1> registrarClaveDigitalAsync(DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigital registrarClaveDigital) {
            DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.registrarClaveDigitalRequest();
            inValue.registrarClaveDigital = registrarClaveDigital;
            return ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).registrarClaveDigitalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse1 DinersClubOnline.Services.Client.SeguridadService.Seguridad.validarTarjeta(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest request) {
            return base.Channel.validarTarjeta(request);
        }
        
        public DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse validarTarjeta(DinersClubOnline.Services.Client.SeguridadService.validarTarjeta validarTarjeta1) {
            DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest();
            inValue.validarTarjeta = validarTarjeta1;
            DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse1 retVal = ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).validarTarjeta(inValue);
            return retVal.validarTarjetaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse1> DinersClubOnline.Services.Client.SeguridadService.Seguridad.validarTarjetaAsync(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest request) {
            return base.Channel.validarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.validarTarjetaResponse1> validarTarjetaAsync(DinersClubOnline.Services.Client.SeguridadService.validarTarjeta validarTarjeta) {
            DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.validarTarjetaRequest();
            inValue.validarTarjeta = validarTarjeta;
            return ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).validarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse1 DinersClubOnline.Services.Client.SeguridadService.Seguridad.validarTarjetaUsuario(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest request) {
            return base.Channel.validarTarjetaUsuario(request);
        }
        
        public DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse validarTarjetaUsuario(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuario validarTarjetaUsuario1) {
            DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest();
            inValue.validarTarjetaUsuario = validarTarjetaUsuario1;
            DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse1 retVal = ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).validarTarjetaUsuario(inValue);
            return retVal.validarTarjetaUsuarioResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse1> DinersClubOnline.Services.Client.SeguridadService.Seguridad.validarTarjetaUsuarioAsync(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest request) {
            return base.Channel.validarTarjetaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioResponse1> validarTarjetaUsuarioAsync(DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuario validarTarjetaUsuario) {
            DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest inValue = new DinersClubOnline.Services.Client.SeguridadService.validarTarjetaUsuarioRequest();
            inValue.validarTarjetaUsuario = validarTarjetaUsuario;
            return ((DinersClubOnline.Services.Client.SeguridadService.Seguridad)(this)).validarTarjetaUsuarioAsync(inValue);
        }
    }
}
