angular.module('appDinersClubOnline.serviciosSocio', [])
    .controller('ServiciosSocio', ['sessionFactory', '$routeParams', ServiciosSocio.ServiciosSocioController])
    .directive('bloquearTarjeta', () => new Tarjeta.BloquearTarjetaDirective())
    .directive('bloquearTarjetaConfirmacion', () => new Tarjeta.BloquearTarjetaConfirmacionDirective())
    .directive('bloquearTarjetaSeleccion', () => new Tarjeta.BloquearTarjetaSeleccionDirective())
    .controller('CambioClaveDigital', ['usuarioApi', 'authApi', 'sessionFactory', '$q', '$location', '$scope', ServiciosSocio.CambioClaveDigitalController])
    .directive('cambioClaveDigital', () => new ServiciosSocio.CambioClaveDigitalDirective())
    .directive('cambioClaveDigitalIngresar', () => new ServiciosSocio.CambioClaveDigitalIngresarDirective())
    .directive('reclamo', () => new ServiciosSocio.ReclamoDirective())
    .controller('ReclamoIngresar', ['usuarioApi', 'tarjetasApi', 'sessionFactory', '$scope', ServiciosSocio.ReclamoIngresarController])
    .directive('reclamoIngresar', () => new ServiciosSocio.ReclamoIngresarDirective())
    .controller('AlertaNotificacion', ['alertasNotificacionesApi', 'usuarioApi', 'tarjetasApi', 'sessionFactory', '$scope', Alerta.AlertaNotificacionController])
    .directive('alertaNotificacionGestor', () => new Alerta.AlertaNotificacionGestorDirectice())
    .directive('alertaNotificacion', () => new Alerta.AlertaNotificacionDirective);